### ISSUE TITLE
Display Driver Version

### ISSUE THREAD

**Issue by speckm** [Oganisyan/Variometer-LilyGoEPD47#4]
Many thanks for this solution! Great work.

I have a question: This library uses an EPD driver which, e.g. can rotate the display. The official driver from Lilygo, referenced below, seems to be different, as is does e.g. not support rotation yet (which is bad for my current project, where I need portrait mode). 

The version of the Lilygo T5 4.7 inch I bought recently is V2.4, with the esp32s3. 

Can you give me a hint, if the driver used here would work on this as well or where/what driver you used in this project (or did you develop on your own), where I could search for, to get an epd driver with rotation for the V2.4 board. 

Many thanks

Official Driver:
https://github.com/Xinyuan-LilyGO/LilyGo-EPD47

**Comment by Oganisyan** [comment]
Unfortunately, I stopped the project two years ago (hardware was not
sufficient for my requirements).
Maybe the following link will help
you.https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/9


Am Do., 18. Juli 2024 um 08:53 Uhr schrieb Mario Speck <
***@***.***>:

**Comment by speckm** [comment]
Many thanks for the hint. I managed to do a merge of the official Lilygo driver for S3 and the open source EPDIY driver and now have full rotation on the V2.4. Still in beta, but thanks to your hint, I will put this on github once it's finalized.
